@startuml


[*] --> Меню : открыть меню
Меню --> ВыборКатегорииТовара : выбрать товар из меню
ВыборКатегорииТовара --> Комбобургер : выбрать комбобургер
ВыборКатегорииТовара --> ГотовоеБлюдо : выбрать готовое блюдо
Комбобургер --> КонструкторБургера : в конструкторе комбобургера\nвыбрать ингредиенты\nи их последовательность 
КонструкторБургера --> Корзина : добавить собранный\nкомборубкер в корзину
ГотовоеБлюдо --> Корзина : добавить готовое блюдо\nв корзину
Корзина --> ОплатаЗаказа : оплатить заказ
ОплатаЗаказа --> ОплатаБанковскойКартой : оплатить банковской\nкартой
ОплатаЗаказа --> Наличными : оплатить наличными
Наличными --> ТолькоНаличными : оплатить наличными
Наличными --> СмешанняОплата : оплатить наличными\nи бонусами
ОплатаБанковскойКартой --> ТолькоБК : оплатить банковской\nкартой
ОплатаБанковскойКартой --> СмешанняОплата : оплатить банковской\nкартой\nи бонусами
ТолькоБК --> ТранзакцияПроведена : получить подтвержение\nоплаты с терминала
СмешанняОплата --> ТранзакцияПроведена : получить подтвержение\nоплаты с терминала
ТолькоНаличными --> ТранзакцияПроведена : получить подтвержение\nоплаты с терминала
ТранзакцияПроведена --> ВыдачаЧека : получение кассового чека
ВыдачаЧека --> [*]

@enduml