@startuml
Entity Клиент
{
Идентификатор
Номер телефона
}

Entity Меню
{
категория
название
активность
срок действия
}


Entity Товар
{
описание
Цена
калорийность
БЖУ
фотография
Ингридиент
Является сборным продуктом
}


Entity Ингредиент
{
Название
Белки
Жиры
Углеводы
Калории
Цена
Очередность
Комбинируется с...
}

Entity Корзина
{
Товар
Является комбо
Количество товара
}

Entity Заказ
{
Дата
Номер
Статус
Способ получения
Время получения
}

Entity Оплата
{
Способ оплаты
№ банковской карты
Статус оплаты
Чек
Сумма к оплате
Кол-во внесенных средств
Кол-во пораченных балллов
}

Entity БонуснаяСистема
{
Идентификатор клиента
Кол-во балллов
Авторизация
}


Меню "1..*" o-- "1..*" Товар 
Корзина "1" -- "1..*" Товар
Заказ "1" --^ "1" Корзина
Товар "1..*" o-- "1..*" Ингредиент
Клиент "1" --> "0..*" Заказ
Клиент "1" -- "1" Корзина
Оплата -- БонуснаяСистема
Клиент "1" *-- "1" БонуснаяСистема
Заказ "1..1" *-- "1..1" Оплата
Товар "1" o-- "1..*" Товар
Ингредиент -- Ингредиент


'Клиент "0..1" --> "0..*" Покупка : генерализация
'Клиент --^ Покупка : наследование
'Клиент --* Покупка : композиция
'Клиент --o Покупка : агрегация
'Клиент -- Покупка : ассоциация
@enduml