@startuml
left to right direction
:Клиент: as Cs
:Менеджер \n по гостеприимству: as M
:Менеджер \n по ассортименту: as Ma
:Работник пополнения: as Rp
rectangle Заказ {
(оформить заказ \n в зале или на вынос) as Cs1
(Просмотр меню) as Cs2
(Зарегестирироваться \n в системе) as Cs3
(Информация о готовности \n на информационном \n табло) as Cs5
(Получение заказа) as Cs6
(Оплатить заказ) as Cs9
(Авторизоваться \n в системе) as Cs10
(Оформить отказ \n от покупки \n и вернуть деньги) as M1
(Возврат наличных) as M2
(Возврат при оплате \n банковской картой) as M3
(Получение информации о сбоях) as M4
(Обновление информации о меню) as M5
}

rectangle Производство {
(Обновить меню) as Ma1
(Отображение информации \n о состоянии роботов) as Ma2
(Информация о необходимости \n пополнения роботов \n полуфабрикотами) as Ma3
(Настройка технологических карт) as Ma4
}


M --> M1
M1 <|-- M2
M1 <|-- M3
Cs --> Cs1
Cs --> Cs5
Cs --> Cs6
M --> Cs6
M --> M4
M --> M5
M5 <.. Ma1 : extend
Cs1 ..> Cs2 : include
Cs1 <.. Cs3 : extend
Cs1 <.. Cs10
Cs1 ..> Cs9 : include
Cs6 ..> M1 : include
Ma --> Ma1
Ma --> Ma2
Ma --> Ma4
Ma2 ..> Ma3 : include
M4 ..> Ma2 : include
Rp --> Ma3

@enduml