@startuml
left to right direction
:Клиент: as Cs
:Менеджер: as M
:Менеджер \n по ассортименту: as Ma
rectangle Оформление {
(оформить заказ \n и получить талон) as Cs1
(Просмотр меню) as Cs2
(Зарегестирироваться \n в системе) as Cs3
( "в зале" или \n "на вынос" ) as Cs4
(Информация о готовности \n на информационном \n табло) as Cs5
(Выдача заказа) as Cs6
(Предъявление талона) as Cs7
(Оформить отказ \n от покупки \n и вернуть деньги) as M1
(Возврат наличных) as M2
(Возврат при оплате \n банковской картой) as M3
(Получение информации о сбоях) as M4
}
rectangle Производство {
(Обновить меню) as Ma1
(Отображение информации \n о состоянии роботов) as Ma2
(Информация о необходимости \n пополнения роботов \n полуфабрикотами) as Ma3

}

M --> M1
M1 <.. M2 : include
M1 <.. M3 : include
Cs --> Cs1
Cs --> Cs5
Cs --> Cs6
M --> Cs6
M --> M4
Cs1 ..> Cs2 : extend
Cs1 <.. Cs3 : include
Cs1 <.. Cs4 : include
Cs6 <.. Cs7 : include
Ma -up-> Ma1
Ma -up-> Ma2
Ma2 <.. Ma3 : include
Cs2 <.. Ma1 : extend
M4 ..> Ma2 : include

@enduml